//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenthreadwithBreeze.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GoldenThreadEntities : DbContext
    {
        public GoldenThreadEntities()
            : base("name=GoldenThreadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Voice> Voices { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
    
        public virtual ObjectResult<USP_GetTagsByAPIId_Result> USP_GetTagsByAPIId(Nullable<int> apiid)
        {
            var apiidParameter = apiid.HasValue ?
                new ObjectParameter("apiid", apiid) :
                new ObjectParameter("apiid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetTagsByAPIId_Result>("USP_GetTagsByAPIId", apiidParameter);
        }
    
        public virtual ObjectResult<USP_GetVoiceAuthorsByAPIId_Result> USP_GetVoiceAuthorsByAPIId(Nullable<int> apiid)
        {
            var apiidParameter = apiid.HasValue ?
                new ObjectParameter("apiid", apiid) :
                new ObjectParameter("apiid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetVoiceAuthorsByAPIId_Result>("USP_GetVoiceAuthorsByAPIId", apiidParameter);
        }
    
        public virtual int USP_GoldenThreadApplicationAdd(Nullable<int> createdBy)
        {
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_GoldenThreadApplicationAdd", createdByParameter);
        }
    
        public virtual int USP_GoldenThreadAuthorAdd(string iDFacebook, string iDTwitter, string iDGoogle, string iDInstagram, string status, Nullable<int> userID, Nullable<int> createdBy)
        {
            var iDFacebookParameter = iDFacebook != null ?
                new ObjectParameter("IDFacebook", iDFacebook) :
                new ObjectParameter("IDFacebook", typeof(string));
    
            var iDTwitterParameter = iDTwitter != null ?
                new ObjectParameter("IDTwitter", iDTwitter) :
                new ObjectParameter("IDTwitter", typeof(string));
    
            var iDGoogleParameter = iDGoogle != null ?
                new ObjectParameter("IDGoogle", iDGoogle) :
                new ObjectParameter("IDGoogle", typeof(string));
    
            var iDInstagramParameter = iDInstagram != null ?
                new ObjectParameter("IDInstagram", iDInstagram) :
                new ObjectParameter("IDInstagram", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_GoldenThreadAuthorAdd", iDFacebookParameter, iDTwitterParameter, iDGoogleParameter, iDInstagramParameter, statusParameter, userIDParameter, createdByParameter);
        }
    
        public virtual int USP_GoldenThreadChapterAdd(Nullable<int> iDApp, string title, Nullable<int> createdBy)
        {
            var iDAppParameter = iDApp.HasValue ?
                new ObjectParameter("IDApp", iDApp) :
                new ObjectParameter("IDApp", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_GoldenThreadChapterAdd", iDAppParameter, titleParameter, createdByParameter);
        }
    
        public virtual int USP_GoldenThreadVoiceAdd(Nullable<int> authorID, string status, string type, string image, string video, string text, Nullable<int> tagID, Nullable<int> iDChapter, Nullable<int> createdBy)
        {
            var authorIDParameter = authorID.HasValue ?
                new ObjectParameter("AuthorID", authorID) :
                new ObjectParameter("AuthorID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            var videoParameter = video != null ?
                new ObjectParameter("Video", video) :
                new ObjectParameter("Video", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var tagIDParameter = tagID.HasValue ?
                new ObjectParameter("TagID", tagID) :
                new ObjectParameter("TagID", typeof(int));
    
            var iDChapterParameter = iDChapter.HasValue ?
                new ObjectParameter("IDChapter", iDChapter) :
                new ObjectParameter("IDChapter", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_GoldenThreadVoiceAdd", authorIDParameter, statusParameter, typeParameter, imageParameter, videoParameter, textParameter, tagIDParameter, iDChapterParameter, createdByParameter);
        }
    
        public virtual int USP_GoldenThreadVoiceEdit(Nullable<int> iD, Nullable<int> authorID, string status, string type, string image, string video, string text, Nullable<int> iDChapter, Nullable<int> createdBy)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var authorIDParameter = authorID.HasValue ?
                new ObjectParameter("AuthorID", authorID) :
                new ObjectParameter("AuthorID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            var videoParameter = video != null ?
                new ObjectParameter("Video", video) :
                new ObjectParameter("Video", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var iDChapterParameter = iDChapter.HasValue ?
                new ObjectParameter("IDChapter", iDChapter) :
                new ObjectParameter("IDChapter", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_GoldenThreadVoiceEdit", iDParameter, authorIDParameter, statusParameter, typeParameter, imageParameter, videoParameter, textParameter, iDChapterParameter, createdByParameter);
        }
    
        public virtual ObjectResult<USP_GetVoiceByAPIId_Result> USP_GetVoiceByAPIId(Nullable<int> apiid)
        {
            var apiidParameter = apiid.HasValue ?
                new ObjectParameter("apiid", apiid) :
                new ObjectParameter("apiid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetVoiceByAPIId_Result>("USP_GetVoiceByAPIId", apiidParameter);
        }
    
        public virtual int USP_GoldenThreadChapterDelete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_GoldenThreadChapterDelete", iDParameter);
        }
    
        public virtual int USP_GoldenThreadChapterEdit(Nullable<int> iD, Nullable<int> iDApp, string title, Nullable<int> modifiedBy)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iDAppParameter = iDApp.HasValue ?
                new ObjectParameter("IDApp", iDApp) :
                new ObjectParameter("IDApp", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_GoldenThreadChapterEdit", iDParameter, iDAppParameter, titleParameter, modifiedByParameter);
        }
    }
}
