//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenthreadwithBreeze.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Voice
    {
        public int ID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Image { get; set; }
        public string Video { get; set; }
        public string Text { get; set; }
        public Nullable<int> IDChapter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> IDTag { get; set; }

          [JsonIgnore]
        public virtual Author Author { get; set; }
          [JsonIgnore]
        public virtual Chapter Chapter { get; set; }
          [JsonIgnore]
        public virtual Tag Tag { get; set; }
    }
}
